# =======================================================================================================================================================================
# Aeon.LinearDrive CI/CD
# =======================================================================================================================================================================
# Index:
# * Build interface
# * Publish packages to GitHub
# * Publish packages to NuGet.org
# =======================================================================================================================================================================
# Note that this is a generic workflow meant for all Harp devices. Minor local modifications are fine, see https://github.com/bonsai-rx/prefect for more information.
# Documentation is handled centrally and the MicroPython firmware is flashed manually, so this workflow has no DocFX or firmware jobs.
# =======================================================================================================================================================================
name: Aeon.LinearDrive
on:
  push:
    # This prevents tag pushes from triggering this workflow
    branches: ['**']
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  ContinuousIntegrationBuild: true
jobs:
  # =====================================================================================================================================================================
  # Build interface
  #  ___      _ _    _   _     _            __
  # | _ )_  _(_) |__| | (_)_ _| |_ ___ _ _ / _|__ _ __ ___
  # | _ \ || | | / _` | | | ' \  _/ -_) '_|  _/ _` / _/ -_)
  # |___/\_,_|_|_\__,_| |_|_||_\__\___|_| |_| \__,_\__\___|
  #
  # =====================================================================================================================================================================
  build-interface:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows x64
            os: windows-latest
          - name: Linux x64
            os: ubuntu-latest
        configuration: ['debug', 'release']
        include:
          - platform:
              os: windows-latest
            configuration: release
            collect-packages: true
    name: ${{matrix.platform.name}} ${{matrix.configuration}}
    runs-on: ${{matrix.platform.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Set up .NET tools
        run: dotnet tool restore

      - name: Configure build
        id: configure-build
        uses: bonsai-rx/configure-build@v2

      - name: Regenerate interface
        run: dotnet harp.toolkit generate interface -o software/${{github.workflow}} --namespace ${{github.workflow}}

      - name: Verify generated code is up-to-date
        run: |
          git add . --intent-to-add --ignore-removal
          git diff --name-status --exit-code

      - name: Restore
        run: dotnet restore software

      - name: Build
        run: dotnet build software --no-restore --configuration ${{matrix.configuration}}

      - name: Pack
        id: pack
        run: dotnet pack software --no-restore --no-build --configuration ${{matrix.configuration}}

      - name: Collect NuGet packages
        uses: actions/upload-artifact@v7
        if: matrix.collect-packages && steps.pack.outcome == 'success' && always()
        with:
          name: Packages
          if-no-files-found: error
          path: artifacts/package/${{matrix.configuration}}/**

  # =====================================================================================================================================================================
  # Publish packages to GitHub
  #  ___      _    _ _    _                    _                      _          ___ _ _   _  _      _
  # | _ \_  _| |__| (_)__| |_    _ __  __ _ __| |____ _ __ _ ___ ___ | |_ ___   / __(_) |_| || |_  _| |__
  # |  _/ || | '_ \ | (_-< ' \  | '_ \/ _` / _| / / _` / _` / -_|_-< |  _/ _ \ | (_ | |  _| __ | || | '_ \
  # |_|  \_,_|_.__/_|_/__/_||_| | .__/\__,_\__|_\_\__,_\__, \___/__/  \__\___/  \___|_|\__|_||_|\_,_|_.__/
  #                             |_|                    |___/
  # =====================================================================================================================================================================
  publish-github:
    name: Publish packages to GitHub
    runs-on: ubuntu-latest
    needs: build-interface
    permissions:
      # Needed to attach files to releases
      contents: write
      # Needed to upload to GitHub Packages
      packages: write
    if: github.event_name == 'push' || github.event_name == 'release'
    steps:
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Download built packages
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: artifacts/packages/

      - name: Upload release assets
        if: github.event_name == 'release'
        run: gh release upload --repo ${{github.repository}} ${{github.event.release.tag_name}} artifacts/packages/* --clobber
        env:
          GH_TOKEN: ${{github.token}}

      - name: Push to GitHub Packages
        run: dotnet nuget push "artifacts/packages/*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/${{github.repository_owner}}
        env:
          # This is a workaround for https://github.com/NuGet/Home/issues/9775
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0

  # =====================================================================================================================================================================
  # Publish packages to NuGet.org
  #  ___      _    _ _    _                    _                      _         _  _       ___     _
  # | _ \_  _| |__| (_)__| |_    _ __  __ _ __| |____ _ __ _ ___ ___ | |_ ___  | \| |_  _ / __|___| |_   ___ _ _ __ _
  # |  _/ || | '_ \ | (_-< ' \  | '_ \/ _` / _| / / _` / _` / -_|_-< |  _/ _ \ | .` | || | (_ / -_)  _|_/ _ \ '_/ _` |
  # |_|  \_,_|_.__/_|_/__/_||_| | .__/\__,_\__|_\_\__,_\__, \___/__/  \__\___/ |_|\_|\_,_|\___\___|\__(_)___/_| \__, |
  #                             |_|                    |___/                                                    |___/
  # =====================================================================================================================================================================
  publish-packages-nuget-org:
    name: Publish packages to NuGet.org
    runs-on: ubuntu-latest
    environment: public-release
    needs: build-interface
    if: github.event_name == 'release'
    steps:
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Download built packages
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: artifacts/packages/

      - name: Push to NuGet.org
        run: dotnet nuget push "artifacts/packages/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source ${{vars.NUGET_API_URL}}
        env:
          # This is a workaround for https://github.com/NuGet/Home/issues/9775
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
